### ISSUE TITLE
Bug: GitHub Actions Workflow Failed to Push Updates Due to Repository Rules

### ISSUE THREAD

**Issue by keli-wen** [LLMQuant/quant-wiki#64]
## Description

The `run quant_scholar` GitHub Action workflow is failing when attempting to push changes to the repository. The error occurs during the "Commit and push changes" step with the following message:

```
remote: error: GH013: Repository rule violations found for refs/heads/master.
remote: Review all repository rules at https://github.com/LLMQuant/quant-wiki/rules?ref=refs%2Fheads%2Fmaster
remote: - Changes must be made through a pull request.
```

The repository has branch protection rules that require changes to be made through pull requests, which prevents the workflow from directly pushing updates to the main branch.

## Solution

To resolve this issue while maintaining security best practices, we'll implement a Deploy Keys approach that allows the GitHub Action to bypass branch protection rules:

1. Generate an SSH key pair specifically for this workflow:
   ```bash
   ssh-keygen -t ed25519 -C "github-actions-deploy-key" -f deploy_key
   ```
   This creates two files: `deploy_key` (private key) and `deploy_key.pub` (public key).

2. Add the public key as a Deploy Key in the repository:
   - Go to repository "Settings" > "Deploy keys"
   - Click "Add deploy key"
   - Add a title like "GitHub Actions Update Docs"
   - Paste the contents of `deploy_key.pub`
   - Check "Allow write access"
   - Click "Add key"

3. Store the private key as a repository secret:
   - Go to repository "Settings" > "Secrets and variables" > "Actions"
   - Add a new secret named `DEPLOY_KEY` with the contents of the `deploy_key` file

4. Update the workflow YAML to use the SSH key for authentication:
   ```yaml
   name: run quant_scholar
   on:
     schedule:
       - cron: '0 0 */2 * *'  # Runs at 00:00 UTC, every 2 days
     workflow_dispatch:
   jobs:
     update-docs:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout repo-b
           uses: actions/checkout@v3
           with:
             repository: LLMQuant/quant-wiki
             ssh-key: ${{ secrets.DEPLOY_KEY }}
             
         - name: Fetch wiki/index.md from quant-scholar
           run: |
             curl -o index.md https://raw.githubusercontent.com/LLMQuant/quant-scholar/main/wiki/index.md
             
         - name: Replace index.md with wiki/index.md
           run: |
             mv index.md docs/scholar/index.md
             
         - name: Commit and push changes
           run: |
             git config --global user.name "GitHub Actions"
             git config --global user.email "actions@github.com"
             git add docs/scholar/index.md
             git commit -m "[Workflow] Automated update of paper list from quant-scholar"
             git push
   ```

5. Add Deploy Keys to the Bypass list in Branch Protection settings:
   - Go to repository "Settings" > "Branches" > "Branch protection rules"
   - Edit the protection rule for the master branch
   - In the bypass section, ensure "Deploy keys" is checked
   - Save changes

This solution provides repository-specific authentication without using personal credentials, limits access to only this specific repository, allows permissions to be revoked at any time, and follows the principle of least privilege for better security.
